### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by dead10ck**
- **fix: handle process shutdown with limited permissions**

Certain platforms like Android do not have permission to list all child processes. In this instance, just continue

- **remove dsa keys from test setup**

DSA has been removed from openssh for some time now, and this causes running tests on newer machines to fail

### CODE REVIEW

**Comment by dmurphy18** [comment]
@dwoz How do you feel about removing dsa keys from salt-factories ?

**Comment by dmurphy18** [comment]
@dead10ck Even though the failures may not be due to your changes, can you look into why the tests are failing, wondering about that 3006.0 and 3007.0 given those are not the most recent versions of those branches

**Comment by dmurphy18** [comment]
@dead10ck Going to merge in your changes and I shall fix up the GitHub Actions , for example: Python 3.7 and 3.8, need to go, both EOL

**Review by dmurphy18 — APPROVED** [review]

**Comment by dmurphy18** [comment]
@dead10ck Note: pytest-salt-factories version 1.0.3 which has your fix is now available from PyPI. Note is uses an older version of pytest-shell-utilities since Salt 3006.x and 3007.x both make use of psutil < 6.0.0 (5.8.x and 5.9.x).
Will be taking about upping the psutil dependencies in Salt team standup tomorrow, but you have to run with what is already released.

**Comment by dead10ck** [comment]
Sounds good, thank you!

**Pull request merged**
